name: Build

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --fix-missing gcc libgl1-mesa-dev xorg-dev
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o SongConverter .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-linux
          path: SongConverter

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o SongConverter.exe .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-windows
          path: SongConverter.exe

  build-macos-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o SongConverter-intel .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-macos-intel
          path: SongConverter-intel

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o SongConverter-arm64 .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-macos-arm64
          path: SongConverter-arm64
