name: Build

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.21'
          cache: false
      - name: Install dependencies
        run: sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o SongConverter .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-linux
          path: SongConverter

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.21'
          cache: false
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -o SongConverter.exe .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-windows
          path: SongConverter.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.21'
          cache: false
      - name: Tidy
        run: go mod tidy
      - name: Build (Intel)
        run: GOARCH=amd64 go build -o SongConverter-intel .
      - name: Build (Apple Silicon)
        run: GOARCH=arm64 go build -o SongConverter-arm64 .
      - uses: actions/upload-artifact@v4
        with:
          name: SongConverter-macos
          path: |
            SongConverter-intel
            SongConverter-arm64
