name: Upload Assets to Release

on:
  release:
    types: [created, published]
  workflow_dispatch: # Allows you to trigger this manually from the "Actions" tab

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./assets
          merge-multiple: true

      - name: Display downloaded files (Debug)
        run: ls -R ./assets

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          # This will attach the files to the release that triggered the event
          files: |
            ./assets/SongConverter.tar.xz
            ./assets/SongConverter.exe
            ./assets/SongConverter-intel.zip
            ./assets/SongConverter-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
